baseURL = "/"
languageCode = "en-us"
title = "Ruben Krueger"
themesDir = "themes"
theme = "hugo-winston-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = "@rubenkrueger_"
  showAuthorOnHomepage = true
  showAuthorOnPosts = true
  showPostsOnHomepage = false
  addFrame = true
  addDot = true

[taxonomies]
  category = 'categories'
  tag = 'tags'

[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "title"
    weight = 30

  [[related.indices]]
    name = "description"
    weight = 30

  [[related.indices]]
    name = "tags"
    weight = 30

  [[related.indices]]
    name = "date"
    weight = 10


[ markup.goldmark ]
[ markup.goldmark.extensions]
    table = true
